import { Sparkles, Zap, Infinity } from "lucide-react";

export const PRICING_PLANS = [
  {
    id: "free",
    name: "Rascunho",
    price: "R$ 0",
    period: "",
    subtitle: "Grátis",
    description: "Teste todos os recursos antes de publicar",
    icon: "Sparkles",
    iconColor: "text-gray-500",
    badge: undefined,
    features: [
      "Crie memórias completas",
      "Teste todos os recursos",
      "Upload ilimitado de fotos (teste)",
      "Edição completa",
      "Preview em tempo real",
      "Sem cartão de crédito",
    ],
    limitations: [
      "❌ Link de compartilhamento bloqueado",
      "Apenas você pode ver",
    ],
    cta: "Começar Grátis",
    href: "/dashboard",
    highlighted: false,
  },
  {
    id: "standard",
    name: "1 Ano",
    price: "R$ 29,90",
    period: "Pagamento Único",
    subtitle: "Hospedagem por 1 ano",
    description: "Perfeito para presentes e ocasiões especiais",
    icon: "Zap",
    iconColor: "text-violet-600",
    badge: undefined,
    features: [
      "✨ Pagamento Único",
      "Hospedagem por 1 ano",
      "Até 15 Fotos",
      "Música de fundo",
      "Link de compartilhamento liberado",
      "Sem marca d'água",
    ],
    cta: "Escolher Plano",
    href: "/login",
    highlighted: false,
  },
  {
    id: "eternal",
    name: "Vitalício",
    price: "R$ 49,90",
    period: "Pagamento Único",
    subtitle: "Nunca expira",
    description: "Suas memórias preservadas para sempre",
    icon: "Infinity",
    iconColor: "text-pink-600",
    badge: "Mais Escolhido",
    features: [
      "✨ Pagamento Único",
      "Hospedagem Eterna (Nunca expira)",
      "Até 50 Fotos",
      "Suporte a Vídeo e Áudio (Voz)",
      "Proteção por Senha",
      "Download das fotos originais",
      "Suporte prioritário",
    ],
    cta: "Escolher Vitalício",
    href: "/login",
    highlighted: true,
  },
] as const;

export type PricingPlan = typeof PRICING_PLANS[number];
